version: 0.0
os: linux
files:
  - source: ./
    destination: /app
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 3600
  Install:
    - location: scripts/install.sh
