version: 0.2

phases:
  install:
    commands:
      - echo Entering the install phase...
      - apt update && apt upgrade -y
      - apt install build-essential -y
      - python -m pip install --upgrade pip
  build:
    commands:
      - echo Entering the build phase...
      - python -m pip install -r requirements.txt
