version: '3'
services:
  dev: &dev
    build: .
    image: amedeiros/algo-bot-dev
    command: ["bash"]
    env_file: bot-variables.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
  bot:
    <<: *dev
    command: ["hy", "./algo_bot/run.hy"]
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algo-bot
    volumes:
      - .dbdata:/var/lib/mysql
    depends_on:
      - adminer
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: "redis"
    ports:
      - 6379:6379
    volumes:
      - cache:/data
  lock-requirements:
    <<: *dev
    depends_on: []
    entrypoint: "/bin/bash"
    command: "lock-requirements.sh"
volumes:
  cache:
