version: '3'
services:
  dev: &dev
    build: .
    image: amedeiros/algo-bot-dev
    command: ["bash"]
    env_file: bot-variables.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - workers
  bot:
    <<: *dev
    command: ["python", "./algo_bot/run.py"]
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: algo-bot
    volumes:
      - dbdata:/var/lib/mysql
    depends_on:
      - adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  worker-ui:
    <<: *dev
    command: ["flower","-A", "algo_bot.worker.app", "-l", "info", "--address=0.0.0.0", "--broker=redis://redis:6379/0", "--broker_api=redis://redis:6379/0"]
    depends_on:
      - redis
      - db
    ports:
      - 5555:5555
  workers:
    <<: *dev
    command: ["celery", "-A", "algo_bot.worker.app", "worker", "-E", "-B", "-l", "INFO"]
    depends_on:
      - redis
      - db
      - worker-ui
  redis:
    image: "redis"
    ports:
      - 6379:6379
    volumes:
      - cache:/data
  lock-requirements:
    <<: *dev
    depends_on: []
    entrypoint: "/bin/bash"
    command: "lock-requirements.sh"
volumes:
  dbdata:
  cache:
